name: CI

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Import smoke test
        run: |
          python -c "import numpy, pandas, networkx, matplotlib"
          python -c "import pandapower"
          python -c "import torch"
          python -c "import torch_geometric"
